name: Hello-World

# Run this workflow every time a new commit pushed to your repository
# Todo change this to PR
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  hello-world:
    # Name the Job
    name: Test hello world
    # Set the type of machine to run on
    runs-on: ubuntu-20.04

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Get Code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          tools: phpunit:6
      - name: Run Hello World
        run: php Devel/scripts/helloWorld.php
